version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.0
    - 1.12.1
    - 1.8.1
    - 1.9.0
    - 1.9.1
  - dependency-name: bootsnap
    versions:
    - 1.6.0
    - 1.7.0
    - 1.7.1
    - 1.7.2
    - 1.7.3
  - dependency-name: capistrano3-puma
    versions:
    - 5.0.2
    - 5.0.3
  - dependency-name: capistrano
    versions:
    - 3.15.0
  - dependency-name: webpacker
    versions:
    - 5.2.1
  - dependency-name: administrate
    versions:
    - 0.14.0
  - dependency-name: rollbar
    versions:
    - 3.1.1
