# To start all docker containers run: `docker-compose up`
#
version: '3'
services:
  app:
    build: .
    command: bash -c "bundle install && bundle exec rake db:create db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
      - "4000:4000" # for headless chrome to be able to connect to our app server
    depends_on:
      - db
      - mailcatcher
      - chrome
    volumes:
      - .:/app:cached
      - gem_cache:/gems
    tty: true
    environment:
      - SKYLIGHT_DISABLE_DEV_WARNING=true
      - DATABASE_HOST=db
      - DATABASE_USERNAME=ubuntu
      - DATABASE_PASSWORD=password
    stdin_open: true
  mailcatcher:
    build: .
    command: bash -c "gem install mailcatcher && mailcatcher --ip 0.0.0.0 --no-quit -f"
    ports:
      - "1025:1025"
      - "1080:1080"
    volumes:
      - .:/app:cached
      - gem_cache:/gems
    tty: true
    stdin_open: true

  db:
    image: postgres:9.6.11
    restart: always
    environment:
      POSTGRES_USER: ubuntu
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_development
    volumes:
      - db-data:/var/lib/postgresql/data
    logging:
      driver: none
  # For system-tests
  chrome:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none
    ports:
      - "5900:5900"
volumes:
  db-data:
    driver: local
  gem_cache: {}
